module.exports = Object.freeze({
    TBL_USER:'tbl_users',
    TBL_DONATION:'tbl_donation_details',
    TBL_DONATION_ITEM:'tbl_donation_items',
    TBL_OTP:'tbl_otp',
    TBL_ROLE:'tbl_roles',
    TBL_USERS_ROLES:'tbl_users_roles',
    TBL_PASSWORD_RESET:'tbl_password_resets',
    TBL_ITEM:'tbl_items',
    TBL_NEW_DONATION:'tbl_donations',
    TBL_ELEC_DONATION:'tbl_elec_donation',
    TBL_ELEC_DONATION_ITEM:'tbl_elec_donation_item',
    TBL_MANUAL_DONATION:'tbl_manual_donation',
    TBL_MANUAL_DONATION_ITEM:'tbl_manual_donation_item',
    TBL_VOUCHERS:'tbl_vouchers',
    TBL_DONATION_TYPES:'tbl_donation_types',
    TBL_EMPLOYEES:'tbl_employees',
    TBL_ADMIN : 'tbl_admin',
    TBL_EMP_ROLES: 'tbl_emp_roles',
    TBL_RECEIPT:'tbl_receipt',
    TBL_CHECKIN:'tbl_checkin',
    TBL_ROOMS:'tbl_rooms',
    TBL_HOLDIN:'tbl_holdin',
    TBL_ROOM_CATEGORY:'tbl_rooms_category',
    TBL_FACILITY:'tbl_facility',
    Tbl_CANCELLEDVOUCHERS:'tbl_cancelled_vouchers',
    Tbl_DHARAMSALA: 'tbl_dharmasala',
    TBL_BOLIHEAD:'tbl_boli_head',
    TBL_BOLI: 'tbl_boli',
    TBL_BOLIUNIT: 'tbl_boli_unit',
    TBL_BOLI_ITEM: 'tbl_boli_item',
    TBL_TRUST: 'tbl_trust',
    TBL_BOLI_PAYMENT: 'tbl_boli_payment',
    TBL_TRUST_TYPE: 'tbl_trust_type',
    TBL_SADSYA_TYPE: 'tbl_sadsya_type',
    TBL_RELATIONSHIP_TYPE: 'tbl_relationship_type',
    TBL_COMMITTEE: 'tbl_committee',
    TBL_OCCASION_TYPE: 'tbl_occasion_type',
    TBL_FAMILY: 'tbl_families',
    TBL_FAMILY_MEMBERS: 'tbl_family_members',
    TBL_VEHICLE_TYPE: 'tbl_vehicle_type',
    TBL_VEHICLE: 'tbl_vehicle',
    TBL_MATERIAL: 'tbl_material',
    TBL_MATERIAL_ITEM: 'tbl_material_item',
    TBL_EMPLOYEE_TYPE: 'tbl_employee_type',
    TBL_BANK_NAME: 'tbl_bank_name',
    TBL_DEPARTMENT: 'tbl_department',
    TBL_LEAVE_TYPE: 'tbl_leave_type',
    TBL_EMPLOYEE_STATUS: 'tbl_employee_status',
    TBL_HR_EMPLOYEE: 'tbl_hr_employee',
    TBL_BOLI_GROUP: 'tbl_boli_group',
    TBL_BOLI_LEDGER: 'tbl_boli_ledger',
    TBL_BOLI_VOUCHER: 'tbl_boli_voucher',
    TBL_BOLI_VOUCHER_LIST: 'tbl_boli_voucher_list',
    TBL_EMPLOYEE_LEAVE: 'tbl_employee_leave',
    TBL_DESIGNATION: 'tbl_designation',
    TBL_DISABLE_DHARAMSHALA: 'tbl_disable_dharamshala',
    TBL_EMPLOYEE_ATTENDANCE: 'tbl_employee_attendance',
    TBL_EMPLOYEE_SALARY: 'tbl_employee_salary',
    TBL_EXPENSE_GROUP: 'tbl_expense_group',
    TBL_EXPENSE_LEDGER: 'tbl_expense_ledger',
    TBL_EXPENSE_VOUCHER: 'tbl_expense_voucher',
    TBL_EXPENSE_VOUCHER_LIST: 'tbl_expense_voucher_list',
    TBL_PAYMENT_MODE: 'tbl_payment_mode',
    TBL_PURCHASE_REQUISITION: 'tbl_purchase_requisition',
    TBL_PURCHASE_REQUISITION_LIST: 'tbl_purchase_requisition_list',
    TBL_PURCHASE_ORDER: 'tbl_purchase_order',
    TBL_PURCHASE_ORDER_LIST : 'tbl_purchase_order_list',
    TBL_PAYMENT_IN: 'tbl_payment_in',
    TBL_GATE_ENTRY: 'tbl_gate_entry',
    TBL_GATE_ENTRY_LIST: 'tbl_gate_entry_list',
    TBL_INVOICE: 'tbl_invoice',
    TBL_CUSTOM_WHATSAPP: 'tbl_custom_whatsapp',
    TBL_EXPENSE_HEAD: 'tbl_expense_head',
    TBL_SUPPLIER_NAME: 'tbl_supplier_name',
    TBL_BHOJNALAY: 'tbl_bhojnalay',
    TBL_BHOJNALAY_HEAD : 'tbl_bhojnalayHead',
    TBL_UOM: 'tbl_uom',
    TBL_PAYMENT_TYPE: 'tbl_payment_type',
    TBL_INVENTORY: 'tbl_inventory',
    TBL_INVENTORY_LIST: 'tbl_inventory_list',
    TBL_STOCK: 'tbl_stock',
    TBL_ITEM_HEAD: 'tbl_item_head'
}); 